version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing app dependencies...
      - yarn install
  build:
    commands:
      - echo Building static site...
      - yarn build
      - echo Run tests...
      - CI=true yarn test

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build

cache:
  paths:
    - './node_modules/**/*'